### ISSUE TITLE
`npm start validate` Emits a Bunch of Errors

### ISSUE THREAD

**Issue by bookercodes** [javascriptair/site#97]
Hm... :confused: 

I'm trying to follow the [setup instructions found in CONTRIBUTING.md](https://github.com/javascriptair/site/blob/master/CONTRIBUTING.md).

I cloned the repository and ran `npm install` then `npm start validate`. `npm install` works but `npm start validate` emits a bunch of errors:

```
→ npm start validate                                                                 [c74e061]
p-s executing: npm run start build -s
p-s executing: p-s -p eslint,build.home,build.episodes,build.guests,build.deals,build.css,build.contributors,createJson
p-s executing: eslint .
p-s executing: babel-node generate/home
p-s executing: ./scripts/build-episodes.sh
p-s executing: rimraf guests && mkdir guests && babel-node generate/guests
p-s executing: rimraf deals && mkdir deals && babel-node generate/deals
p-s executing: postcss -u postcss-import -u postcss-nested -u postcss-mixins -u autoprefixer -u cssnano resources/css/styles.css > styles.dist.css
p-s executing: rimraf contributors && mkdir contributors && babel-node generate/contributors
p-s executing: babel-node generate/json-files
/home/booker/Code/site/generate/write-to-json-file.js:19
function writeJsonArray(arrayNewItems, config, applyFilter = false) {
                                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (json-files.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (home.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (contributors.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (guests.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
episodes built 😎
/home/booker/Code/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/home/booker/Code/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/booker/Code/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (deals.js:2:1)
    at Module._compile (module.js:413:34)
```

**Comment by kentcdodds** [comment]
Sorry, I need to update the `CONTRIBUTING.md` to indicate that the project now requires Node 6. I did this because it speeds up build times because we need to transpile much less.
