### ISSUE TITLE
npm start validate - errors

### ISSUE THREAD

**Issue by timarney** [javascriptair/site#99]
Im getting the following error(s) when running npm start validate

node v5.5.0
npm  v3.9.3

```
/Users/timarney/Documents/jsair/site/generate/renderComponentToFile.js:21
  const { html, css } = _aphrodite.StyleSheetServer.renderStatic(() => {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)


...


SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at loader (/Users/timarney/Documents/jsair/site/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/timarney/Documents/jsair/site/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (episode.js:2:1)
    at Module._compile (module.js:413:34)
episodes built 😎
/Users/timarney/Documents/jsair/site/generate/write-to-json-file.js:19
function writeJsonArray(arrayNewItems, config, applyFilter = false) {
                                                           ^
```

**Comment by timarney** [comment]
Found - https://github.com/javascriptair/site/issues/97
